# 设置端口
server:
  port: 8070

# 配置阿里云短信服务
aliyun:
  sms:
    accessKeyId: LTAI4FkZJ7i8PzgzUpx54xrZ   #创建的accesskey中的AccessKey ID
    accessKeySecret: fZuwZ3iRjNRiNgaiIFSTnW1shJ67hS      #创建的accesskey中的Access Key Secret
    template_code: SMS_175571377      #模板管理中的模板CODE
    sign_name: 智取乐食       #签名管理中的签名

# 配置日志
logging:
  level:
    com:
      duanxin:
        zqls:
          ucenter: debug

# 配置dubbo
dubbo:
  protocol:
    name: dubbo
  registry:
    address: zookeeper://39.106.154.120:2181
  consumer:
    check: false
    loadbalance: roundrobin
  application:
    name: ucenter-web